# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-19 14:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='Articale',
        ),
    ]
