# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-25 03:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20161120_0505'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quanzhifashi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='章节')),
                ('url', models.CharField(max_length=30, verbose_name='url')),
            ],
        ),
    ]
