# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-10 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20170110_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='标签名'),
        ),
    ]
