# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-16 01:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('file_name', models.CharField(max_length=70, verbose_name='文件名')),
                ('file_length', models.IntegerField(verbose_name='文件大小')),
                ('desc', models.CharField(max_length=120, null=True, verbose_name='描述')),
                ('file_path', models.FilePathField(verbose_name='文件地址')),
            ],
        ),
    ]
