# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-16 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formupload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemodel',
            name='file',
            field=models.FileField(default='asd', upload_to=''),
        ),
    ]
