# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-25 03:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formupload', '0002_filemodel_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemodel',
            name='file',
            field=models.FileField(default='asd', upload_to='upload_file/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='filemodel',
            name='file_length',
            field=models.IntegerField(null=True, verbose_name='文件大小'),
        ),
    ]
